### ISSUE TITLE
default /admin route error if dashboard page renamed

### ISSUE THREAD

**Issue by smpallen99** [ex-admin/ex_admin#69]
I renamed a the dashboard page to info. I get an error could not render "dashboard.html".

**Comment by smpallen99** [comment]
With update c277edb, the work around  is to override the `page/2` action in your page controller and change the default like this:

```elixir
defmodule MyApp.Web.TalonPageController do
  # ...
  def page(conn, params) do
    page = Map.get(params, "page", "info") # default will be the info page.
    render(conn, "#{page}.html")
  end
end
```

**Comment by smpallen99** [comment]
@dsnider I did some investigation into our options for handling the default `/admin` route. I was not able to find the topic I saw in the past, nor could I find out how to set the params inside a match.

I believe we could do this with a plug, but I'm not sure that's the best option. 

I believe the best approach would be to have a controller in Talon (not in the project space to handle this specific case. That controller action could look at possible configuration (don't know where to put that) and if not found, then search in the following order. first page, first resource, some text indicating that no pages/resource have been configured.

If a page or resource is found, the action can just call the action on the appropriate controller after setting up the params correctly.

**Comment by dsnider** [comment]
Bummer. I tried for a while to get that to work to no avail. It would be ideal to have this handled there.

What I was doing previously was routing to :dashboard action on page controller. Perhaps :default or :root would have been a better action name. That same approach could be a work around above -- instead of overriding page, add a :default or :root action then route to that and prime the :page param there. 

I like the idea of a policy for looking up a default page. I'm not sure if it should a resource should be a default candidate, though. That might be confusing? Not sure.  Also, is it considered bad form in Phoenix to call the action of another controller directly? 

Adding a DefaultController or RootController would work, but I'd prefer to have an easy way to override the policy. If we only create in Talon space, changing the policy wouldn't be as obvious. 

Perhaps PageController could handle this similar to what I was doing before? Add a `:default` or :`root` action and route "/" to that action. The default policy looks for the first defined page or generates some placeholder. This gives the user an easy hook to override in TalonPageController. We could even generate a boiler plate example of such an override that points to a resource.

**Comment by smpallen99** [comment]
The problem is that a project may not have a page controller. It may not even have a resource controller. I think it would be nice to still be able to render a page with instructions on adding a page or resource. 

Your right, calling an action from a controller in Talon will not work. Not because its bad form, but we would be bypassing the plugs for the controller.

We could use the `talon_routes` macro to generate the route based on the pages/resources configuration. And the user can override this by adding their own "/admin" route.

**Comment by dsnider** [comment]
@smpallen99 does PR #73 address your original problem of changing the dashboard to info? After doing the appropriate renames, it appears to work for me. See below.

> We could use the talon_routes macro to generate the route based on the pages/resources configuration. And the user can override this by adding their own "/admin" route.

Are you saying to remove  `get "/", TalonPageController, :index` from our Talon Router and put the onus on the user?  

![image](https://user-images.githubusercontent.com/16876/27562675-9993bfde-5a9b-11e7-8ed8-b775c9af1d92.png)

**Comment by smpallen99** [comment]
Yes Dan. I tried it this morning and worked fine. Also nice that I only had to rename the template directory, and not the template itself.

**Comment by dsnider** [comment]
Okay, I'm closing this but see #79.
