### ISSUE TITLE
Inspiration 

### ISSUE THREAD

**Issue by zimt28** [ex-admin/ex_admin#83]
I haven't actually looked into the current state of talon, but this project might be good to look at: https://trestle.io/ - https://github.com/TrestleAdmin/trestle

Especially the DSL for creating pages looks nice, might be worth a look :-)

**Comment by smpallen99** [comment]
Took a real quick look. Looks similar to ActiveAdmin. We have taken the approach on Talon to move away from DSL and use a more “Phoenix” friendly approach. 

A lot of the “magic” is behind __using__ macros with the injected functions defined as overridable. This makes it very easy to add custom code and the call super to get the built in functionality. 

I think this approach is easier to follow and provides more flexibility for customization.

**Comment by nathanbuchar** [comment]
Hey Steve,

Is this repository still active? ex_admin still doesn't really support the new version of Phoenix out of the box, and when 1.3 was released you moved over to this project and I've been watching it since but it has been mostly dormant for three months.

From what I can find, there are really no other good admin panels out there other than ex_admin so I was excited when I saw you had started working on the Talon framework and I've been holding out hope, but it's been quite a while now and I'm curious as to where it stands.
